apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-feed
  labels:
    app: udagram-api-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-api-feed
  template:
    metadata:
      labels:
        app: udagram-api-feed
    spec:
      containers:
      - name: udagram-api-feed
        image: aryola4/udagram-api-feed
        ports:
          - containerPort: 8080
        envFrom:
          - configMapRef:
              name: env-config
          - secretRef:
              name: env-secret
        volumeMounts:
          - mountPath: "/root/.aws/"
            name: aws-credentials
      volumes:
        - name: aws-credentials
          configMap: 
            name: aws-credentials